# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f54fe54ad4f3a035ef00e8c3a9e11ec588dfe7d8e967c9ac3acea6f89f42e0613b962030677342090330d2deaccbeca21e82b2cb5d5bbf33ea777b320da55b04

test:
  secret_key_base: 929c9cb813db36716ede566249571a556942f177787602923a4a0259cc1d6d66b8d8e00e674870b1c553adb8c99cebb93d38c5a4e65e768ff5fafd7bb9e40fda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
